apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: elastic-operator-crds
  namespace: flux-system
spec:
  interval: 60m
  chart:
    spec:
      chart: eck-operator-crds
      sourceRef:
        kind: HelmRepository
        name: elastic
      interval: 5m
