apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: victoria-metrics
spec:
  interval: 24h
  url: https://github.com/VictoriaMetrics/helm-charts
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include deploy dir
    !/charts/victoria-metrics-operator/charts/crds
