apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-crds
spec:
  interval: 60m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ./charts/victoria-metrics-operator/charts/crds
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: victoria-metrics
        namespace: flux-system
      interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
