apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-operator-crds
spec:
  interval: 60m
  chart:
    spec:
      chart: victoria-metrics-operator-crds
      sourceRef:
        kind: HelmRepository
        name: vm
      interval: 5m
