apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-crds
  namespace: flux-system
spec:
  interval: 60m
  reconcileStrategy: Revision
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: ./charts/victoria-metrics-k8s-stack/charts/crds
      sourceRef:
        kind: GitRepository
        name: victoria-metrics
        namespace: flux-system
      interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
