apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: strimzi
  namespace: flux-system
spec:
  interval: 24h
  url: https://github.com/strimzi/strimzi-kafka-operator.git
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include crd dir
    !/helm-charts/helm3/strimzi-kafka-operator/crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: strimzi
  namespace: flux-system
spec:
  interval: 24h
  path: ./helm-charts/helm3/strimzi-kafka-operator/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: strimzi
