apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Use a specific version instead 'main' if you want to install a specific version
  - https://raw.githubusercontent.com/metallb/metallb/main/charts/metallb/charts/crds/templates/crds.yaml
